import type { Metadata } from "next";
import { fontSans } from "@/lib/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Github Resumes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.variable}>{children}</body>
    </html>
  );
}
